exchange:
  api:
    simulated: true
    base-url: https://api.apilayer.com/exchangerates_data
    api-key: D8FwM98Y6Hq9w8vVqKvZhyT6nx8pj5UJ
#    0N48LEmVqIMNZS08m8NTWdG6ItuYwMVI


spring:
  cache:
    caffeine:
      spec: initialCapacity=200,expireAfterWrite=5m,maximumSize=10000
    cache-names: cacheSymbols


#  cache:
#    cache-names: cacheSymbols
#    caffeine:
##      spec: maximumSize=500,expireAfterAccess=600s
#      spec: initialCapacity=200,expireAfterWrite=5m,maximumSize=10000,recordStats=true
#logging:
#  level:
#    root: INFO
#    pl.szlify.exchangeapi.service: DEBUG



  mail:
    host: smtp.gmail.com
    port: 587
    username: exchangeapka@gmail.com
    password: byqp mmdo avhd yrah
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
