exchange:
  api:
    simulated: true
    base-url: https://api.apilayer.com/exchangerates_data
    api-key: D8FwM98Y6Hq9w8vVqKvZhyT6nx8pj5UJ
#    0N48LEmVqIMNZS08m8NTWdG6ItuYwMVI


spring:
  config:
    import: classpath:secrets.yml
  cache:
    caffeine:
      spec: initialCapacity=200,expireAfterWrite=5m,maximumSize=10000
    cache-names: cacheSymbols
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${spring.security.oauth2.client.registration.google.client-id}
            client-secret: ${spring.security.oauth2.client.registration.google.client-secret}
            scope:
              #              - profile
              - email
          github:
            client-id: ${spring.security.oauth2.client.registration.github.client-id}
            client-secret: ${spring.security.oauth2.client.registration.github.client-secret}



  mail:
    host: smtp.gmail.com
    port: 587
    username: exchangeapka@gmail.com
    password: byqp mmdo avhd yrah
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


logging:
  level:
    org:
      springframework:
        security: TRACE